# Nom de l'application
spring.application.name=congo-telecom

# --- CONFIGURATION MYSQL ---
# Remplace 'sfa_db' par le nom que tu veux donner à ta base
spring.datasource.url=jdbc:mysql://localhost:3306/sfa_db?createDatabaseIfNotExist=true&serverTimezone=UTC
# Mets ici ton nom d'utilisateur MySQL (souvent 'root')
spring.datasource.username=sagesse
# Mets ici ton mot de passe MySQL (laisse vide si tu n'en as pas)
spring.datasource.password=xdapper2000
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- HIBERNATE / JPA (L'outil qui crée les tables) ---
# 'update' veut dire : Spring crée les tables automatiquement s'il voit de nouvelles classes dans le dossier 'model'
spring.jpa.hibernate.ddl-auto=create
# Affiche les requêtes SQL dans la console (très utile pour débugger avec Benicien)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- SERVEUR ---
# Ton application sera accessible sur http://localhost:8080
server.port=8080